# Generated by Django 4.1.7 on 2023-04-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('idproduk', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('gambar', models.ImageField(null=True, upload_to='static/foto/')),
                ('namaproduct', models.CharField(max_length=255)),
                ('hargaproduct', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(max_length=255)),
                ('stok', models.CharField(max_length=6)),
            ],
        ),
    ]
