# Generated by Django 4.1.7 on 2023-04-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='hargaproduct',
            field=models.IntegerField(max_length=255),
        ),
    ]
