# Generated by Django 4.1.7 on 2023-04-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userproduct_hargaproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='hargaproduct',
            field=models.IntegerField(),
        ),
    ]
