# Generated by Django 4.1.7 on 2023-04-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userproduct_hargaproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='gambar',
            field=models.ImageField(null=True, upload_to='static/assets/dist/img/'),
        ),
    ]
