# Generated by Django 4.1.7 on 2023-04-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userproduct_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/dist/img'),
        ),
    ]
