# Generated by Django 4.1.7 on 2023-04-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userproduct_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('idpemesanan', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('tglpemesanan', models.DateField()),
                ('jumlahpemesanan', models.IntegerField()),
                ('totalbayar', models.IntegerField()),
                ('keterangan', models.CharField(max_length=255)),
                ('idmakanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userproduct')),
            ],
        ),
    ]
