# Generated by Django 4.1.7 on 2023-04-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pemesanan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pemesanan',
            old_name='idmakanan',
            new_name='idproduk',
        ),
    ]
