# Generated by Django 4.1.7 on 2023-04-24 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hargajual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stok_terjual', models.IntegerField(default=0)),
                ('total_terjual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('idpemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pemesanan')),
                ('idproduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userproduct')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
