# Generated by Django 4.1.7 on 2023-04-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_penjualan_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penjualan',
            old_name='stok_terjual',
            new_name='stok',
        ),
        migrations.RemoveField(
            model_name='penjualan',
            name='idpemesanan',
        ),
        migrations.AlterField(
            model_name='penjualan',
            name='total_terjual',
            field=models.IntegerField(default=0),
        ),
    ]
