# Generated by Django 4.1.7 on 2023-05-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_transaksi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='idpemesanan',
        ),
    ]
