# Generated by Django 4.1.7 on 2023-05-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_transaksi_idpemesanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='statuspembayaran',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
