# Generated by Django 4.1.7 on 2023-05-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_pemesanan_statuspembayaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('idnotifikasi', models.AutoField(primary_key=True, serialize=False)),
                ('pesannotifikasi', models.CharField(max_length=225)),
                ('statusnotifikasi', models.CharField(max_length=1)),
            ],
        ),
    ]
